---
- name: stop containers
  docker_container:
    name: "{{ stop_item }}"
    state: stopped
  loop: "{{ stop_containers_before }}"
  loop_control:
      loop_var: stop_item

- include_tasks: in_to_volume.yml
  when: direction == "in"

- include_tasks: out_of_volume.yml
  when: direction == "out"

- name: copy data
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image }}"
    purge_networks: true
    cleanup: true
    detach: false
    command: "/bin/sh -c \"ls -la / && {{ docker_command }}\""
    mounts:
      - read_only: true
        source: "{{ src_mount }}"
        target: "/src"
        type: "{{ src_mount_type }}"
      - source: "{{ dest_mount }}"
        target: "/dest"
        type: "{{ dest_mount_type }}"
- name: start containers
  docker_container:
    name: "{{ start_item }}"
    state: started
  loop: "{{ start_containers_after | default(stop_containers_before) }}"
  loop_control:
      loop_var: start_item
